name: PipeLine Commit

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy HTML
        run: |
        if [[ `git status --porcelain` ]]; then
          git add -A
          git commit -m "Atualização automática do HTML"
          git push origin main
        else
          echo "Nada para commitar, árvore de trabalho limpa"
        fi
